In [14]:
import numpy as np

In [18]:
array1d = np.array([5,6,4,3,7,8,9])
array1d

array([5, 6, 4, 3, 7, 8, 9])

In [15]:
array = np.random.randint(0,30, size=(3,3))

array

array([[ 2,  0, 15],
       [10, 16, 22],
       [12, 21,  2]])

In [16]:
array_array = np.arange(0,40,4)
array_array

array2= array_array.reshape(5,2)
array2

array([[ 0,  4],
       [ 8, 12],
       [16, 20],
       [24, 28],
       [32, 36]])

### Index array 1D

In [22]:
# Como em listas
array1d[0]
array1d[1]
array1d[2]

4

### Index array 2D

In [29]:
# Primeiro numero: Linha
# Segundo numero: Col

array2[0,1]
array[1,2]

22

In [31]:
array[0] # Pega todos os itens da linha

array([ 2,  0, 15])

### Slicing

### :,

In [33]:
array2[:,0] # Pega todos os itens da coluna

#:, significa todos os itens
# segunda posição = col

array([ 0,  8, 16, 24, 32])

In [34]:
array[:,1]

array([ 0, 16, 21])

In [35]:
array1d[0:4] # Do index 0 ao 4

array([5, 6, 4, 3])

In [39]:
array[1:3, 0:2] # Da linha 1 a 3 a Coluna 0 a 2

array([[10, 16],
       [12, 21]])

### Sorting

In [40]:
np.sort(array) # Por default organiza em ordem crescente as colunas

array([[ 0,  2, 15],
       [10, 16, 22],
       [ 2, 12, 21]])

In [42]:
np.sort(array, axis=0)

array([[ 2,  0,  2],
       [10, 16, 15],
       [12, 21, 22]])

In [43]:
np.sort(array, axis=1)

array([[ 0,  2, 15],
       [10, 16, 22],
       [ 2, 12, 21]])

# Atividades

Explorando Ecossistemas:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

<strong>ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie</strong>

* Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
* De qtd_especies selecione apenas as primeiras 3 quantidades e print
* Print as 5 últimas quantidades de espécies
* Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente

In [74]:
especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [75]:
qntd_especies = especies[:,1]
qntd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [46]:
tres_primeiras = qntd_especies[0:3]
tres_primeiras

array([ 89, 123,  22])

In [52]:
cinco_ultimas = qntd_especies[-5:]
cinco_ultimas

array([ 64,  84, 105, 103, 124])

In [73]:
tamanhos = especies[:,3]
tamanhos

array([ 5, 13,  2, 10, 22,  7, 14, 16,  5,  1])

In [76]:
tamanhos_ordenados = np.sort(tamanhos)
tamanhos_ordenados

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

In [78]:
np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

In [80]:
np.sort(especies[:,3])[::-1] # [::-1] todas as linhas e todas as colunas -1 (decrescente)

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])