In [3]:
import numpy as np

In [10]:
pessoas_id_idade = np.array([[1,22],[2,21],[3,27],[4,26]])
pessoas_id_idade

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [19]:
cartela_bingo = np.random.randint(2,30, size=(4,4))
cartela_bingo

array([[ 5, 29,  9,  6],
       [19,  7, 18,  3],
       [10, 27, 27, 11],
       [18, 12, 16, 17]])

In [29]:
array = np.arange(0,30,1)
array = array.reshape(6,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Mask

Aplica uma condição no array que retorna booleanos 

In [15]:
mask = pessoas_id_idade[:,1] % 2 == 0 #
mask

array([ True, False, False,  True])

### Fancy indexing

Aplicando no array a variavel mascarada em formato de índice, irá filtrar apenas os resultados que apresentam a condição da mascará

In [17]:
pessoas_id_idade[mask]

array([[ 1, 22],
       [ 4, 26]])

### np.where()

* Retorna um array informando onde se localiza o índice do resultado
* Cria uma matriz com base se os elementos correspondem ou não a condição
* Busca e substitui

In [20]:
np.where(cartela_bingo % 2 ==0)

(array([0, 1, 2, 3, 3, 3], dtype=int64),
 array([3, 2, 0, 0, 1, 2], dtype=int64))

(array([0, 1, 2, 3, 3, 3], dtype=int64), <strong>linha</strong>

 array([3, 2, 0, 0, 1, 2], dtype=int64)) <strong>coluna</strong>

In [22]:
np.where(pessoas_id_idade[:,1]% 2 ==0)

(array([0, 3], dtype=int64),)

In [31]:
np.where(array[0:4, 0:3] % 2 == 0, "viado", "sapatao") #np.where(array[indexacao ou tudo só nao colocar] condicao, "aplica isso","não aplica")

array([['viado', 'sapatao', 'viado'],
       ['sapatao', 'viado', 'sapatao'],
       ['viado', 'sapatao', 'viado'],
       ['sapatao', 'viado', 'sapatao']], dtype='<U7')

In [34]:
np.where(cartela_bingo % 2 == 0, 999999, 1)

array([[     1,      1,      1, 999999],
       [     1,      1, 999999,      1],
       [999999,      1,      1,      1],
       [999999, 999999, 999999,      1]])

In [45]:
p = np.where(pessoas_id_idade >= 22, "maior de idade", pessoas_id_idade )
p

array([['1', 'maior de idade'],
       ['2', '21'],
       ['3', 'maior de idade'],
       ['4', 'maior de idade']], dtype='<U14')

In [48]:
print(type(p))
print(p.dtype)

<class 'numpy.ndarray'>
<U14


In [49]:
print(type(p[0,0]))

<class 'numpy.str_'>


# Atividade

Ainda usando o Array de espécies marítimas.
* Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.
* Usando fency index faça um array que contém apenas dados da espécie com ID 297
* Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
* Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo"

In [52]:
# ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie

especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])

In [82]:
mask = especies[:,3] >= 22
mask

array([False, False, False, False,  True, False, False, False, False,
       False])

In [83]:
especies[mask]

array([[297,  56,  69,  22]])

In [89]:
id297 = especies[:,0] == 297
id297

array([False, False, False, False,  True, False, False, False, False,
       False])

In [90]:
especies[id297]

array([[297,  56,  69,  22]])

In [104]:
mask = especies[:,1] == 105
mask

array([False, False, False, False, False, False, False,  True, False,
       False])

In [105]:
reshape = especies[mask]
reshape

array([[692, 105,  72,  16]])

In [106]:
reshape.reshape(4,1)

array([[692],
       [105],
       [ 72],
       [ 16]])

In [115]:
profundos = np.where(especies[:,2]>= 60, "profundo", especies[:,2]) # A condição else tem que ter o mesmo formato do if pois estamos filtrando apenas 1 coluna e varias linhas não podemos retornar uma matriz 2d por exemplo
profundos

array(['33', '32', '49', '42', 'profundo', '27', '29', 'profundo', '35',
       'profundo'], dtype='<U11')