In [1]:
import numpy as np

In [16]:
# Arrays podem ser criados através de listas

l = [1,2,3,4,5,6]
l

[1, 2, 3, 4, 5, 6]

### np.array()

In [59]:
# Array de 1 dimensão tamanho 6
array_1d = np.array(l)
array_1d

(6,)


In [18]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [37]:
# Array de 2 dimensões primeira dimensão:2 segunda dimensão: 5

array2d = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(array2d)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [61]:
print(array2d.shape) # Primeira dimensão tamanho 2, Segunda dimensão tamanho 5
print(array2d.ndim)

(2, 5)
2


### np.zeros()

In [41]:
# Cria array com zeros
# np.zeros recebe uma tupla

zeros_array = np.zeros(shape = (5,3,6)) # Shape = (tamanho da 1º dimensao (qnt arrays 2D), tamanho da 2º dimensao (linhas), tamanho da 3º dimensao(colunas))
zeros_array

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

### np.ones()

In [42]:
# Cria array com uns

ones = np.ones(2)
ones # 1 dimensão com 2 colunas

array([1., 1.])

In [44]:
ones2 = np.ones([2,3])
ones2 # Primeira dimensão com tamanho 2, segunda dimensão com tamanho 3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
print(ones2.shape)
print(ones2.ndim)

(2, 3)
2


### np.ramdom.ramdom()

In [92]:
# Cria um array com valores randomicos de 0 a 1
# np.random.random recebe uma tupla!

array_randomico = np.random.random((2,3))
array_randomico

array([[0.00494273, 0.87622235, 0.83104724],
       [0.50962466, 0.05974031, 0.52249324]])

### np.empty()

In [2]:
# Cria array não vazio

nao_vazio = np.empty([5,2]) # Array 1º dimensao: tamanho 2, 2ºdimensao: tamanho 3
nao_vazio

array([[2.44088554e-154, 1.03845125e-028],
       [4.83245961e+276, 9.08367229e+223],
       [6.01347002e-154, 1.14448609e+243],
       [1.94210903e+227, 9.13612771e+242],
       [6.62274284e+265, 1.87673449e-152]])

In [3]:
print(type(nao_vazio))

<class 'numpy.ndarray'>


### np.arange()

In [4]:
# Cria um array aleatório a partir de um intervalo setado pulando de x em x
arr = np.arange(30,200,20)
arr

array([ 30,  50,  70,  90, 110, 130, 150, 170, 190])

In [7]:
print(arr.size)

9


In [9]:
arr.reshape(3,3)

array([[ 30,  50,  70],
       [ 90, 110, 130],
       [150, 170, 190]])

### np.delete()

In [14]:
dados = np.random.randint(0,40, size=(4,4))
dados

array([[ 1, 17,  0,  0],
       [31, 38, 37,  1],
       [23,  0, 16, 30],
       [25, 21, 34, 26]])

In [15]:
# Indicamos o array
# Idicamos o indice que queremos deletar
# Indicamos o eixo

dados = np.delete(dados, 2, axis=1)
dados

array([[ 1, 17,  0],
       [31, 38,  1],
       [23,  0, 30],
       [25, 21, 26]])

In [24]:
sala_espera = np.array([
['5',6,7, 'Ana Lice'],
['6',8,9, 'Roger'],
['7',19,2, 'Lucia'],
['9',11,1, 'Firmino']
]
)
sala_espera

array([['5', '6', '7', 'Ana Lice'],
       ['6', '8', '9', 'Roger'],
       ['7', '19', '2', 'Lucia'],
       ['9', '11', '1', 'Firmino']], dtype='<U11')

In [25]:
sala_espera = np.delete(sala_espera, 2, axis= 0)
sala_espera

array([['5', '6', '7', 'Ana Lice'],
       ['6', '8', '9', 'Roger'],
       ['9', '11', '1', 'Firmino']], dtype='<U11')

### Modificando o shape do Array

### .reshape()

In [22]:
arr = np.array([[1,2,3,4],[5,4,3,2]]) # 2D array: primeira dimensão = linha, segunda dimensão = coluna
arr

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [23]:
arr.reshape(4,2) # Modificando o shape para o contrario

array([[1, 2],
       [3, 4],
       [5, 4],
       [3, 2]])

### Descobrindo tamanhos de arrays

### .shape() .size() .ndim()

In [56]:
print(zeros_array.shape)
print(zeros_array.size)
print(zeros_array.ndim)

(5, 3, 6)
90
3


### Transformando vetor 1D em matriz 2D

### np.newaxis

In [57]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [64]:
b = a[np.newaxis,:] # newaxis cria um novo eixo para coluna
b # 1 dimensão com tamanho 1 e a outra dimensão com tamanho 4

array([[1, 2, 3, 4]])

In [65]:
print(b.shape)
print(b.ndim)

(1, 4)
2


In [66]:
c = a[:,np.newaxis] # newaxis cria um novo eixo para linha
c # Primeira dimensão com tamanho 4 segunda dimensão com tamanho 1

array([[1],
       [2],
       [3],
       [4]])

In [67]:
print(c.shape)
print(c.ndim)

(4, 1)
2


### Transformando array 2d em 1d
### np.flatter()

In [19]:
# Transforma um array 2d em 1d

array = np.random.randint(0, 11, size=(2,3))
array 

array([[ 1, 10,  6],
       [ 0,  2, 10]])

In [20]:
array.flatten()

array([ 1, 10,  6,  0,  2, 10])

### Concatenando arrays 

### np.concatenate()

In [17]:
x = np.array([1,2,3,4,5])
z = np.array([10,20,30,40,50])


In [18]:
w = np.concatenate((z,x))
w

array([10, 20, 30, 40, 50,  1,  2,  3,  4,  5])

In [22]:
k=w.reshape((5,2))
k

array([[10, 20],
       [30, 40],
       [50,  1],
       [ 2,  3],
       [ 4,  5]])

In [82]:
print(w.shape)
print(w.ndim)

(10,)
1


In [24]:
array1_2d = np.array([[10,20,39],[40,50,60]])
array2_2d = np.array([[70,80,90],[2,3,4]])
array3_2d = np.array([[6,4,65],[2,8,10]])

In [25]:
array3d = np.array((array1_2d, array2_2d, array3_2d)) 
array3d

array([[[10, 20, 39],
        [40, 50, 60]],

       [[70, 80, 90],
        [ 2,  3,  4]],

       [[ 6,  4, 65],
        [ 2,  8, 10]]])

In [28]:
array4d = np.array((array3d, array3d)) 
array4d

array([[[[10, 20, 39],
         [40, 50, 60]],

        [[70, 80, 90],
         [ 2,  3,  4]],

        [[ 6,  4, 65],
         [ 2,  8, 10]]],


       [[[10, 20, 39],
         [40, 50, 60]],

        [[70, 80, 90],
         [ 2,  3,  4]],

        [[ 6,  4, 65],
         [ 2,  8, 10]]]])

In [29]:
print(array4d.shape)
print(array4d.ndim)

(2, 3, 2, 3)
4


Concatenando colunas

In [12]:
arroz = np.array([[1,2,3,4,5],[1,2,3,4,5]])
coluna_adicional = np.array([4,5]).reshape(2,1)


In [13]:
u = np.concatenate((arroz,coluna_adicional), axis=1)
u

array([[1, 2, 3, 4, 5, 4],
       [1, 2, 3, 4, 5, 5]])

In [16]:
dados = np.random.randint(0,40, size=(4,4))
dados

array([[ 1,  0,  7, 12],
       [ 2, 26, 18, 31],
       [ 3, 12,  4,  0],
       [25, 29, 22, 19]])

In [17]:
cartela1 = dados[1:3, 0:2]
cartela1

array([[ 2, 26],
       [ 3, 12]])

In [18]:
cartela2 = dados[1:3, 2:4]
cartela2

array([[18, 31],
       [ 4,  0]])

In [20]:
final = np.concatenate((cartela1,cartela2))
final

array([[ 2, 26],
       [ 3, 12],
       [18, 31],
       [ 4,  0]])

### Convertendo tipos de dados dos Arrays

### .astype()

In [14]:
# dtype como argumento

array_test = np.array([8,9,10,11], dtype=np.int64)
print(array_test.dtype)

int64


In [15]:
# astype

arr_bol_to_int = np.array([[True,False], [True,True]], dtype=np.bool8)
arr_bol_to_int.astype(np.int32)

C:\Users\znaya\AppData\Local\Temp\ipykernel_4024\4153112444.py:3: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  arr_bol_to_int = np.array([[True,False], [True,True]], dtype=np.bool8)


array([[1, 0],
       [1, 1]])

#### Crie um array com valores inteiros 3 linhas e 5 colunas

In [103]:
aleatorio_int = np.random.randint(10, 100, size=(3,5))
aleatorio_int

array([[13, 30, 18, 39, 52],
       [94, 83, 91, 81, 63],
       [65, 65, 69, 72, 98]])

#### Crie um array com 5 colunas e 10 linhas inicializados com zeros

# Atividades

In [96]:
array_zeros = np.zeros((2,2))
array_zeros
print("-----")
print(array_zeros.shape)
print(array_zeros.ndim)

-----
(2, 2)
2


#### Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [93]:
random = np.random.random((4,3))
random

array([[0.76601065, 0.80649833, 0.31939626],
       [0.79939317, 0.60885916, 0.43490742],
       [0.17194644, 0.92257407, 0.97664503],
       [0.7452769 , 0.2956045 , 0.24125504]])

#### Crie um array que vá entre 0 e 90 pulando de 4 em 4

In [5]:
array_array = np.arange(0,91,4)
array_array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

#### Reduza o array (5,7) em apenas uma dimensão

In [ ]:
arr = np.zeros((5,7))
arr.ndim
arr.shape


(5, 7)

In [39]:
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [43]:
arr = arr.flatten()
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [46]:
arr.ndim

1

#### Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. os números da suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4, 3). Crie um array que represente esse jogo

In [48]:
bingo = np.random.randint(1,31, size=(10,4,3)) # Size: 1º dimensão com 10 cartelas (10 matrizes 2d), 2º dimensão com 4 linhas (numeros da cartela) 3º com 3 colunas (numeros da cartela)
bingo

array([[[ 2, 27,  7],
        [25,  3, 18],
        [25,  2,  6],
        [ 5, 11,  8]],

       [[19, 27,  4],
        [16, 29, 21],
        [ 8, 11, 29],
        [12, 21, 26]],

       [[15, 10, 13],
        [18, 26,  1],
        [30, 10, 22],
        [21,  8, 23]],

       [[27, 17, 20],
        [14, 23, 30],
        [ 8, 28, 22],
        [ 8,  2, 28]],

       [[ 2, 19, 28],
        [25, 22, 14],
        [14, 16, 14],
        [18, 13, 19]],

       [[ 3, 13,  3],
        [ 2, 17, 15],
        [ 6,  4,  3],
        [24, 15, 28]],

       [[ 4, 26, 17],
        [ 7, 24,  2],
        [24, 11, 20],
        [22,  9, 16]],

       [[ 6,  4, 10],
        [ 4, 15,  1],
        [27,  7, 23],
        [12, 12, 15]],

       [[30, 25, 25],
        [ 8, 26,  6],
        [13, 29, 13],
        [28, 30, 10]],

       [[29,  4, 27],
        [13, 22, 19],
        [10, 13, 30],
        [ 4, 24, 17]]])

#### Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [49]:
new_bingo = bingo.reshape((5,4,6))
new_bingo

array([[[ 2, 27,  7, 25,  3, 18],
        [25,  2,  6,  5, 11,  8],
        [19, 27,  4, 16, 29, 21],
        [ 8, 11, 29, 12, 21, 26]],

       [[15, 10, 13, 18, 26,  1],
        [30, 10, 22, 21,  8, 23],
        [27, 17, 20, 14, 23, 30],
        [ 8, 28, 22,  8,  2, 28]],

       [[ 2, 19, 28, 25, 22, 14],
        [14, 16, 14, 18, 13, 19],
        [ 3, 13,  3,  2, 17, 15],
        [ 6,  4,  3, 24, 15, 28]],

       [[ 4, 26, 17,  7, 24,  2],
        [24, 11, 20, 22,  9, 16],
        [ 6,  4, 10,  4, 15,  1],
        [27,  7, 23, 12, 12, 15]],

       [[30, 25, 25,  8, 26,  6],
        [13, 29, 13, 28, 30, 10],
        [29,  4, 27, 13, 22, 19],
        [10, 13, 30,  4, 24, 17]]])

## 1.3 No conjunto 'especies'.

*   Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
*   Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]
* Faça um array com todas as especies menos as com ID 623, 116,613


In [29]:
#ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie
especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [31]:
new_especies = np.array(
    [[204, 10, 40, 12], 
     [392, 11, 81, 11]]

)
new_especies

array([[204,  10,  40,  12],
       [392,  11,  81,  11]])

In [32]:
especies = np.concatenate((especies, new_especies))
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [41]:
col_visao = np.array(
[[0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,1]]
).reshape(12,1)
col_visao

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]])

In [44]:
especies = np.concatenate((especies,col_visao), axis=1)
especies

array([[747,  89,  33,   5,   0,   0,   0],
       [623, 123,  32,  13,   1,   1,   1],
       [501,  22,  49,   2,   0,   0,   0],
       [116, 101,  42,  10,   0,   0,   0],
       [297,  56,  69,  22,   0,   0,   0],
       [613,  64,  27,   7,   0,   0,   0],
       [295,  84,  29,  14,   1,   1,   1],
       [692, 105,  72,  16,   0,   0,   0],
       [229, 103,  35,   5,   1,   1,   1],
       [374, 124,  70,   1,   1,   1,   1],
       [204,  10,  40,  12,   0,   0,   0],
       [392,  11,  81,  11,   1,   1,   1]])

In [53]:
especies = np.delete(especies,5,axis=1)

In [55]:
especies

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1]])

In [67]:
# Faça um array com todas as especies menos as com ID 623, 116,613

novas_especies = np.delete(especies,1,axis=0)
novas_especies

array([[747,  89,  33,   5,   0],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1]])

In [68]:
novas_especies = np.delete(novas_especies,2,axis=0)
novas_especies

array([[747,  89,  33,   5,   0],
       [501,  22,  49,   2,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1]])

In [70]:
novas_especies  = np.delete(novas_especies,3,axis=0)
novas_especies

array([[747,  89,  33,   5,   0],
       [501,  22,  49,   2,   0],
       [297,  56,  69,  22,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1]])