In [3]:
import numpy as np

In [25]:
arr = np.array([[1,2],[4,5]])
arr

array([[1, 2],
       [4, 5]])

### Operações Python vs Numpy

Ao realizar a soma de elementos em um array utilizando o NumPy, a operação não ocorre de forma <strong>individual</strong> para cada elemento; em vez disso, ela é realizada de maneira <strong>simultânea</strong> para todos os elementos
do array.

Por isso não precisamos fazer um loop como em python para alcançar o mesmo resultado

In [24]:
for linha in range(0, 2):
	for coluna in range(0,2):
		arr[linha][coluna]+=3
arr

# ou
# for linha in range(0, arr.shape[0]):
#	for coluna in range(0,arr.shape[1]):
#		arr[linha][coluna]+=3
#arr

array([[4, 5],
       [7, 8]])

Simplificando empregamos um sinal de adição e indicamos ao NumPy o número único que desejamos adicionar a todos os elementos do array.

In [4]:
arr2 = np.array([[1,2],[4,5]])
# Simplificado mesmo resultado
arr2 +=3

In [5]:
arr2

array([[4, 5],
       [7, 8]])

In [7]:
arr3 = np.array([[1,2],[4,5]])
arr3 *= 3
arr3

array([[ 3,  6],
       [12, 15]])

### np.vectorize()

Vetorizar significa que podemos aplicar eficientemente uma função a cada elemento de um array NumPy sem nos preocuparmos com loops explícitos para aplicar em cada elemento.

É útil precisamos operar em arrays, mas temos funções projetadas para operar em valores únicos, como o len retornar apenas o tamanho do array e não seus elementos

In [8]:
arr = np.array(["hello","meninas","coders"])
len(arr) > 5 # Len checa o tamanho de itens do array e não cada item

False

In [12]:
vetorizar_len = np.vectorize(len)

In [14]:
vetorizar_len(arr) > 5

array([False,  True,  True])

In [15]:
mask = vetorizar_len(arr) > 5

In [17]:
arr[mask] # Retorna apenas os maiores que 5

array(['meninas', 'coders'], dtype='<U7')

<strong>Vetorizando uma função

In [27]:
def minha_funcao(x):
    x = x**2 + 3*x + 1
    return x

In [28]:
minha_funcao(2)

11

In [30]:
arr = np.array([[1,2],[4,5]])

In [31]:
vetorizar_funcao = np.vectorize(minha_funcao)

In [32]:
result = vetorizar_funcao(arr)

In [33]:
result

array([[ 5, 11],
       [29, 41]])

### Broadcasting

O Broadcasting permite que o NumPy execute essas operações mesmo quando as dimensões dos arrays não são as mesmas, seguindo um conjunto de regras específicas.

In [62]:
#Broadcasting com colunas

arr3x2 = np.array([[1,2],[4,5],[1,1]])
arr3x2

array([[1, 2],
       [4, 5],
       [1, 1]])

In [63]:
arr3x1 = np.array([1,0,-1]).reshape((3,1))
arr3x1

array([[ 1],
       [ 0],
       [-1]])

In [64]:
arr3x2 + arr3x1

array([[2, 3],
       [4, 5],
       [0, 0]])

In [68]:
#Broadcasting com linhas

rray10 = np.arange(10).reshape(2,5)
rray10

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
r_r = np.array([1,2,3,4,5])
r_r

array([1, 2, 3, 4, 5])

In [70]:
rray10 + r_r

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14]])

In [72]:
#Broadcasting com colunas
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
b = np.arange(2).reshape(2,1)
b

array([[0],
       [1]])

In [76]:
a + b

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])